# Generated by Django 3.1.6 on 2021-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210302_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='프론트엔드', max_length=128),
            preserve_default=False,
        ),
    ]
