# Generated by Django 3.1.6 on 2021-03-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210302_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writer',
            new_name='author',
        ),
    ]
